[package]
name = "foxtk-sys"
version = "0.0.6"
authors = ["Artem V. Ageev <artem.v.ageev@gmail.com>"]
license = "LGPL-2.1-only"
repository = "https://github.com/theavege/foxtk-rs"
description = "Rust bindings for the FOX Toolkit"
keywords = ["FOX", "foxtk"]
categories = ["external-ffi-bindings"]
edition = "2024"
exclude = ["use"]

[build-dependencies]
bindgen = { version = "0.72" }
cc = { version = "1.2", features = ["parallel"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
reqwest = { version = "0.13", features = ["json", "native-tls", "blocking"] }
zip-extract = "0.4"
glob = "0.3"
cmake = "0.1"

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3"
