[package]
name = "foxtk"
version = "0.0.6"
authors = ["Artem V. Ageev <artem.v.ageev@gmail.com>"]
license = "LGPL-2.1-only"
repository = "https://github.com/theavege/foxtk-rs"
description = "Rust bindings for the FOX Toolkit"
keywords = ["FOX", "foxtk"]
categories = ["api-bindings", "gui"]
edition = "2024"
exclude = ["examples"]

[dependencies]
foxtk-sys = { path = "../foxtk-sys", version = "=0.0.6"}
paste = { version = "1.0" }
once_cell = { version = "1.18" }

reqwest = { optional = true, version = "0.13", features = ["json", "native-tls", "blocking"] }
xlsxwriter = { optional = true, version = "0" }
chrono = { optional = true, version = "0.4" }

[features]
default = []
reqwest = [ "dep:reqwest" ]
chrono = [ "dep:chrono" ]
xlsxwriter = [ "dep:xlsxwriter" ]
all = ["reqwest", "chrono"]
