[package]
name = "foxtk"
version = "0.0.1"
authors = ["Artem V. Ageev <artem.v.ageev@gmail.com>"]
license = "LGPL"
repository = "https://github.com/theavege/foxtk-rs"
edition = "2024"
exclude = ["examples"]

[dependencies]
foxtk-sys = { path = "../foxtk-sys" }
reqwest = { version = "0.12", features = ["json", "native-tls", "blocking"], optional = true }
xlsxwriter = { version = "0", optional = true }

[features]
default = []
reqwest = [ "dep:reqwest" ]
xlsxwriter = [ "dep:xlsxwriter" ]
all = ["reqwest"]
