---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Build on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euo pipefail
          source '/etc/os-release'
          case ${ID:?} in
            debian | ubuntu) sudo apt-get install -y libfox-1.6-dev ;;
            fedora | alma) sudo apt-get install -y fox-devel ;;
          esac &> /dev/null
          cargo clippy --quiet --example simple
          cargo build --release --example simple
          cargo fmt --check --all

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $installerUrl = 'https://aka.ms/vs/17/release/vs_community.exe'
          $installerPath = Join-Path -Path $env:TEMP -ChildPath 'vs_community_18.exe'
          Write-Host "Downloading Visual Studio 18 Community installer to $installerPath..."
          Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
          $addComponents = @(
            'Microsoft.VisualStudio.Workload.NativeDesktop',
            'Microsoft.VisualStudio.Workload.VCTools',
            'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
            'Microsoft.VisualStudio.Component.Windows11SDK.23000',
            'Microsoft.VisualStudio.Component.VC.CMake.Project',
            'Microsoft.VisualStudio.Component.VC.Redist.14.Latest',
            'Microsoft.VisualStudio.Component.VC.ATL',
            'Microsoft.VisualStudio.Component.VC.ATLMFC',
            'Microsoft.VisualStudio.Component.VC.CoreBuildTools'
          )
          $arguments = @(
            '--quiet',
            '--wait',
            '--norestart',
            '--includeRecommended'
          )
          $addComponents | ForEach-Object { $arguments += "--add $_" }
          Write-Host "Starting Visual Studio 18 Community installer..."
          Start-Process -FilePath $installerPath -ArgumentList $arguments -Wait -NoNewWindow
          Write-Host 'Visual Studio 18 Community installation completed.'
          Write-Host 'If installation fails, rerun the script with administrative privileges.'

